import { csvResults, METRICS, SCENARIOS } from './atlas-data.js';
export function connectAtlas({city,getState,scene,controls,sceneControls,run,render,settings}) {
  const $=id=>document.getElementById(id),stage=$('map-stage');
  stage.insertAdjacentHTML('beforeend',`<div class="map-toolbar" aria-label="3D 지도 도구"><div class="atmospheres" role="group" aria-label="풍경 조명 · 계산 조건과 무관"><button data-atmosphere="day" aria-pressed="true">☀ 낮</button><button data-atmosphere="sunset" aria-pressed="false">◒ 노을</button><button data-atmosphere="night" aria-pressed="false">☾ 밤</button></div><span id="render-mode">경량 3D</span></div><div class="map-tools"><button id="zoom-in" title="확대" aria-label="확대">+</button><button id="zoom-out" title="축소" aria-label="축소">−</button><button id="view-flat" aria-pressed="false" title="평면 보기">2D</button><button id="auto-tour" aria-pressed="false" title="자동 회전">↻</button><button id="fullscreen" title="지도 전체 화면" aria-label="지도 전체 화면">⛶</button></div><div id="cell-inspector" class="cell-inspector"></div><div id="atlas-legend" class="atlas-legend"></div><div class="time-dock"><button id="play-time" aria-label="24시간 변화 재생" aria-pressed="false">▶</button><div class="time-readout"><strong id="time-readout">15:00</strong><span>KST · 모의 시각</span></div><div class="time-slider"><label class="sr-only" for="atlas-hour">모의 시각</label><input id="atlas-hour" type="range" min="0" max="23" value="15"><div><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></div></div>`);
  $('metric-description').insertAdjacentHTML('afterend','<button id="find-hotspot" class="hotspot-button">가장 높은 값의 셀 찾기 ↗</button>');
  document.querySelector('.scene-buttons').insertAdjacentHTML('afterend',`<div class="layer-switches"><label><input id="show-buildings" type="checkbox" checked>집계 건물</label><label><input id="show-heat" type="checkbox" checked>열 색상 격자</label><label><input id="show-hubs" type="checkbox" checked>AI 냉각 거점</label></div><p class="help-text">낮·노을·밤은 풍경 조명입니다. 분석 시각은 지도 아래에서 조정합니다.</p>`);
  document.querySelector('.atlas-footnote').insertAdjacentHTML('afterend',`<div class="atlas-actions"><p>한 셀에 집계한 대표 건물을 표시합니다. 개별 건물의 실측 윤곽이 아닙니다.</p><div><button id="share-view">현재 설정 링크</button><button id="export-csv">결과 CSV ↓</button><button id="export-json">실험 조건 JSON ↓</button></div></div><p id="atlas-notice" role="status" class="atlas-notice"></p>`);
  const notice=text=>{$('atlas-notice').textContent=text;};
  let interval=0;
  const stop=()=>{clearInterval(interval);interval=0;$('play-time').textContent='▶';$('play-time').setAttribute('aria-pressed','false');$('play-time').setAttribute('aria-label','24시간 변화 재생');};
  const syncTime=()=>{$('atlas-hour').value=controls.hour.value;$('time-readout').textContent=String(controls.hour.value).padStart(2,'0')+':00';};
  const setHour=h=>{controls.hour.value=String(h);controls.hour.dispatchEvent(new Event('input',{bubbles:true}));syncTime();};
  $('atlas-hour').addEventListener('input',()=>{stop();setHour(+$('atlas-hour').value);});controls.hour.addEventListener('input',syncTime);
  $('play-time').addEventListener('click',()=>{if(interval){stop();return}if(matchMedia('(prefers-reduced-motion: reduce)').matches){notice('동작 줄이기 설정이 켜져 있습니다. 시간 슬라이더로 시각을 선택하세요.');return}$('play-time').textContent='Ⅱ';$('play-time').setAttribute('aria-label','시간 재생 정지');$('play-time').setAttribute('aria-pressed','true');interval=setInterval(()=>setHour((+controls.hour.value+1)%24),1500);});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();scene.setAuto(false);}});
  const motion=matchMedia('(prefers-reduced-motion: reduce)');motion.addEventListener('change',event=>{if(event.matches){stop();scene.setAuto(false);}});
  document.querySelectorAll('[data-atmosphere]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-atmosphere]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));scene.setAtmosphere(button.dataset.atmosphere);}));
  $('zoom-in').onclick=()=>scene.zoomBy(1.2);$('zoom-out').onclick=()=>scene.zoomBy(.8);$('view-flat').onclick=()=>scene.setFlat();
  $('auto-tour').onclick=()=>{if(motion.matches){notice('동작 줄이기 설정에서는 자동 회전이 꺼집니다.');return}scene.setAuto(!scene.auto);};
  $('find-hotspot').onclick=()=>scene.focusHotspot();
  $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen();}catch{notice('이 브라우저에서는 전체 화면을 사용할 수 없습니다.');}};
  for(const [id,meshes] of [['show-buildings',['buildings','roofs']],['show-heat',['ground']],['show-hubs',['hubs']]])$(id).onchange=()=>{for(const key of meshes)if(scene[key])scene[key].visible=$(id).checked;scene.select(scene.selected);};
  const rendererControls=()=>{const ready=!!scene.webglCanvas;for(const id of ['view-flat','auto-tour','show-buildings','show-heat','show-hubs'])$(id).disabled=!ready;document.querySelectorAll('[data-atmosphere]').forEach(b=>b.disabled=!ready);if(ready)$('render-mode').textContent='3D · WebGL';};
  rendererControls();document.addEventListener('atlas-renderer-ready',rendererControls);
  const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('export-csv').onclick=()=>{const state=getState();if(!state.latest){notice('계산이 끝나면 결과를 저장할 수 있습니다.');return}download(`guwol-heat-${String(state.hour).padStart(2,'0')}h.csv`,csvResults(city,state),'text/csv;charset=utf-8');notice('선택 시각의 모든 셀과 세 시나리오 결과를 CSV로 저장했습니다.');};
  $('export-json').onclick=()=>{const state=getState();if(!state.latest)return;const {calibrationBias,weather,...parameters}=settings();download('guwol-experiment.json',JSON.stringify({version:2,model:'Guwol Heat Atlas',scope:'24 × 18 rectangular grid; representative buildings',parameters,hour:state.hour,metric:sceneControls.metric.value,scenario:sceneControls.scenario.value,sceneIndex:+sceneControls.date.value,referenceWeatherDate:'2024-08-29',seed:8132026,changedCells:state.plan.budgetCount,limitations:'Screening simulation, not measured pedestrian temperature. AI alters both material types and positions.'},null,2),'application/json');notice('재현용 실험 조건을 JSON으로 저장했습니다.');};
  $('share-view').onclick=async()=>{const url=new URL(location.href),params=new URLSearchParams();for(const key of ['hour','air','solar','moisture','budget','wind','objective'])params.set(key,controls[key].value);params.set('metric',sceneControls.metric.value);params.set('scenario',sceneControls.scenario.value);params.set('scene',sceneControls.date.value);url.hash=params.toString();try{await navigator.clipboard.writeText(url.href);notice('현재 실험 조건과 지도 설정의 링크를 복사했습니다.');}catch{const input=document.createElement('input');input.value=url.href;input.readOnly=true;input.setAttribute('aria-label','현재 설정 공유 링크');$('atlas-notice').replaceChildren('링크를 복사하세요: ',input);input.focus();input.select();}};
  function restore(){const p=new URLSearchParams(location.hash.slice(1));for(const key of ['hour','air','solar','moisture','budget','wind']){if(!p.has(key))continue;const el=controls[key],value=Number(p.get(key));if(Number.isFinite(value)&&value>=+el.min&&value<=+el.max)el.value=String(value);}if([...controls.objective.options].some(o=>o.value===p.get('objective')))controls.objective.value=p.get('objective');if(METRICS[p.get('metric')])sceneControls.metric.value=p.get('metric');if(SCENARIOS[p.get('scenario')])sceneControls.scenario.value=p.get('scenario');if(p.has('scene')&&Number.isInteger(+p.get('scene'))&&+p.get('scene')>=0&&+p.get('scene')<sceneControls.date.options.length)sceneControls.date.value=p.get('scene');syncTime();if(p.size)run();}
  restore();window.addEventListener('hashchange',()=>{if(location.hash.includes('='))restore();});
  scene.render();window.addEventListener('beforeunload',()=>{stop();scene.dispose();});
}
