import {analyzeClusters,gridMetrics,summarizeTemperatures,compareObservations,pairSummary} from './research-analysis.js';
import {temperatureColor} from './observed-data.js';
import {MATERIALS} from './materials.js';

const $=id=>document.getElementById(id),finite=Number.isFinite;
const fmt=(v,d=1)=>finite(v)?v.toLocaleString('ko-KR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const signed=v=>finite(v)?`${v>0?'+':''}${fmt(v)}°C`:'—';
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
let dataset,inputs,grid,metrics,sceneIndex=0,clusters,selected=0,pickA=null,pickB=null,experiment=null,validationRows=null,landcover=null;
let requestId=0,activeExperiment=0,activeValidation=0;
const scene=()=>inputs.landsat.scenes[sceneIndex],mask=()=>grid.insideBoundary||dataset.surface.insideBoundary;
const baseImage=new Image();baseImage.src='./data/guwol-osm-basemap.webp';baseImage.onload=()=>{if(inputs){renderObservationMap();if(experiment)renderModels();}};
const worker=new Worker(new URL('./research-worker.js',import.meta.url),{type:'module'});
const modelColors=['#365b49','#d89153','#9c4936'];
const clusterColors=['#152e26','#652d57','#174978','#625317','#603522','#307775'];

function addRow(root,cells) {const row=node('tr');for(const text of cells)row.append(node('td',text));root.append(row);return row;}
function badge(text,warm=false){return node('span',text,`badge${warm?' warm':''}`);}
function dataCard(title,text,url) {const el=node('article',undefined,'card');el.append(node('h3',title),node('p',text));if(url){const a=node('a','출처 확인 ↗');a.href=url;a.target='_blank';a.rel='noopener';el.append(a);}return el;}
function download(name,data,type='text/csv;charset=utf-8'){const blob=new Blob(['\ufeff',data],{type}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csvCell=value=>`"${String(value??'').replaceAll('"','""')}"`;
function canvasContext(canvas) {const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#eef0e7';ctx.fillRect(0,0,canvas.width,canvas.height);if(baseImage.complete&&baseImage.naturalWidth){ctx.globalAlpha=.32;ctx.drawImage(baseImage,0,0,canvas.width,canvas.height);ctx.globalAlpha=1;}return ctx;}
function color(value,min,max,kind='temperature') {
  if(kind==='temperature') return `rgb(${temperatureColor(value,{min,max}).join(',')})`;
  const t=Math.max(0,Math.min(1,(value-min)/(max-min||1)));
  if(kind==='vegetation') return `rgb(${Math.round(224-191*t)},${Math.round(232-130*t)},${Math.round(213-139*t)})`;
  if(kind==='urban') return `rgb(${Math.round(229-120*t)},${Math.round(222-155*t)},${Math.round(218-162*t)})`;
  return `hsl(${(Math.round(value)*47)%360} 36% 60%)`;
}
function drawRaster(canvas,values,{min=24,max=50,kind='temperature',clusterLabels=null,changed=[],hubs=[],picks=[]}={}) {
  const ctx=canvasContext(canvas),cw=canvas.width/grid.width,ch=canvas.height/grid.height;
  values.forEach((v,i)=>{if(!mask()[i]||!finite(v))return;const x=i%grid.width*cw,y=Math.floor(i/grid.width)*ch;ctx.fillStyle=color(v,min,max,kind);ctx.globalAlpha=.8;ctx.fillRect(x,y,cw+.4,ch+.4);});ctx.globalAlpha=1;
  if(clusterLabels) for(let i=0;i<clusterLabels.length;i++){const label=clusterLabels[i];if(!(label>0))continue;const x=i%grid.width,y=Math.floor(i/grid.width);ctx.strokeStyle=clusterColors[(label-1)%clusterColors.length];ctx.lineWidth=Math.max(2,canvas.width/320);ctx.beginPath();if(x===0||clusterLabels[i-1]!==label){ctx.moveTo(x*cw,y*ch);ctx.lineTo(x*cw,(y+1)*ch);}if(x===grid.width-1||clusterLabels[i+1]!==label){ctx.moveTo((x+1)*cw,y*ch);ctx.lineTo((x+1)*cw,(y+1)*ch);}if(y===0||clusterLabels[i-grid.width]!==label){ctx.moveTo(x*cw,y*ch);ctx.lineTo((x+1)*cw,y*ch);}if(y===grid.height-1||clusterLabels[i+grid.width]!==label){ctx.moveTo(x*cw,(y+1)*ch);ctx.lineTo((x+1)*cw,(y+1)*ch);}ctx.stroke();}
  ctx.strokeStyle='#1b604b';ctx.lineWidth=canvas.width/350;for(const i of changed){const x=i%grid.width*cw,y=Math.floor(i/grid.width)*ch;ctx.strokeRect(x+2,y+2,cw-4,ch-4);}
  for(const hub of hubs){const i=typeof hub==='number'?hub:hub.index;if(!Number.isInteger(i))continue;ctx.fillStyle='#183d30';ctx.beginPath();ctx.arc((i%grid.width+.5)*cw,(Math.floor(i/grid.width)+.5)*ch,canvas.width/95,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();}
  for(const {index,label} of picks){if(index===null||index===undefined)continue;const x=(index%grid.width+.5)*cw,y=(Math.floor(index/grid.width)+.5)*ch;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,canvas.width/45,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#174d37';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#174d37';ctx.font=`bold ${canvas.width/45}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x,y);}
  ctx.textAlign='left';ctx.textBaseline='alphabetic';
}

function getLayer(){const key=$('observation-layer').value,s=inputs.sentinel2;
  const defs={lst:{values:scene().values,min:24,max:50,kind:'temperature',label:'Landsat LST',unit:'°C',date:scene().date},ndvi:{values:s.ndvi||[],min:-1,max:1,kind:'vegetation',label:'Sentinel-2 NDVI',unit:'',date:s.scene?.date},ndbi:{values:s.ndbi||[],min:-1,max:1,kind:'urban',label:'Sentinel-2 NDBI',unit:'',date:s.scene?.date},green:{values:dataset.surface.greenFraction,min:0,max:1,kind:'vegetation',label:'OSM 녹지 비율',unit:'',date:dataset.osm.timestampUtc.slice(0,10)},road:{values:dataset.surface.roadFraction,min:0,max:1,kind:'urban',label:'OSM 도로 비율',unit:'',date:dataset.osm.timestampUtc.slice(0,10)},building:{values:dataset.surface.buildingFraction,min:0,max:1,kind:'urban',label:'OSM 건물 비율',unit:'',date:dataset.osm.timestampUtc.slice(0,10)},landcover:{values:landcover?.classes||[],min:0,max:1,kind:'classes',label:'공식 세분류 토지피복',unit:'',date:landcover?.edition||'자료 없음'}};
  return defs[key];
}
function renderObservationMap(){const layer=getLayer();drawRaster($('observation-map'),layer.values,{...layer,clusterLabels:$('show-clusters').checked?clusters?.labels:null,picks:[...(pickA&&pickA.source.id===scene().id?[{index:pickA.index,label:'A'}]:[]),...(pickB&&pickB.source.id===scene().id?[{index:pickB.index,label:'B'}]:[])]});$('map-layer-label').textContent=layer.label;$('map-date').textContent=String(layer.date||'자료 없음');$('map-legend').textContent=layer.kind==='classes'?'범주색 · 실제 재료 판독 아님':`${fmt(layer.min,layer.unit?0:1)} ~ ${fmt(layer.max,layer.unit?0:1)} ${layer.unit} · 색 범위 고정`;
  const key=$('observation-layer').value;$('layer-note').textContent=key==='lst'?'구름·결측은 비워 둡니다. 모든 온도 지도는 24–50°C 고정 범위를 쓰며 범위 밖 값은 끝 색으로 표시합니다.':key==='ndvi'||key==='ndbi'?`Sentinel-2 ${inputs.sentinel2.scene?.date||'자료 없음'} · LST 선택 장면과 ${Math.abs(Date.parse(scene().date)-Date.parse(inputs.sentinel2.scene?.date))/86400000}일 차이. 지수는 재질을 확정하는 측정값이 아닙니다.`:key==='landcover'?`원영상 ${landcover?.imageryDates?.join(', ')||'날짜 미제공'} · 판본과 촬영일을 구별합니다. 토지피복은 지붕 재질이나 알베도의 실측이 아닙니다.`:'OSM 공간 형상에서 집계한 면적 비율입니다. 공식 세분류 토지피복지도와 구별합니다.';
}
function computeClusters(){clusters=analyzeClusters({...grid,projection:'geographic',values:scene().values,mask:mask(),quantile:+$('hot-quantile').value,epsMeters:+$('cluster-eps').value,minPoints:+$('cluster-min').value});
  const root=$('cluster-table');root.replaceChildren();for(const c of clusters.clusters){const row=addRow(root,[`C${c.id}`,`${fmt(c.center[1],5)}, ${fmt(c.center[0],5)}`,fmt(c.areaM2/1e4,2),`${fmt(c.mean)}°C`,`${fmt(c.max)}°C`,fmt(c.count,0)]);row.firstChild.prepend(node('span','', 'pill'));row.firstChild.firstChild.style.background=clusterColors[(c.id-1)%clusterColors.length];}
  if(!clusters.clusters.length)addRow(root,['군집 없음','거리·최소 이웃 조건을 만족하는 고온 군집이 없습니다.','','','','']);
  $('cluster-summary').textContent=`${scene().date} · 기준 ≥ ${fmt(clusters.threshold)}°C · 고온 ${clusters.hotCount}격자 (${fmt(clusters.hotFraction*100)}%) · ${fmt(clusters.hotAreaM2/1e4,2)} ha · ${clusters.clusters.length}개 군집 · 잡음 ${clusters.noiseIndices.length}격자`;
}
function renderObservation(){computeClusters();const summary=summarizeTemperatures({values:scene().values,mask:mask(),areas:metrics.areas,threshold:clusters.threshold});const items=[['구월동 평균 LST',`${fmt(summary.mean)}°C`,'선택 촬영 장면'],['최고 LST',`${fmt(summary.max)}°C`,'분석 격자 평균 중 최고'],['유효 자료',`${fmt(clusters.coverage*100)}%`,`${clusters.validCount} / ${clusters.totalCount}격자`],['고온 영역',`${fmt(clusters.hotAreaM2/1e4,2)} ha`,`≥ ${fmt(clusters.threshold)}°C · 잡음 포함`]];$('observation-metrics').replaceChildren(...items.map(([label,value,note])=>{const el=node('div',undefined,'metric');el.append(node('span',label),node('strong',value),node('small',note));return el;}));
  $('observation-provenance').textContent=`${scene().platform||'Landsat'} · ${scene().datetime.replace('T',' ').slice(0,19)} UTC · QA_PIXEL 구름 제거 후 유효비율 80% 이상 셀을 평균했습니다. 원 열적 해상도 약 100 m. ST_QA 불확실도는 아직 미사용입니다.`;renderObservationMap();renderRelationships();renderCover();renderSelection();
}
function renderRelationships(){const root=$('relationship-table');root.replaceChildren();const s=inputs.sentinel2;const rows=[['Sentinel-2 NDVI',s.ndvi,s.scene?.date],['Sentinel-2 NDBI',s.ndbi,s.scene?.date],['OSM 녹지 비율',dataset.surface.greenFraction,dataset.osm.timestampUtc.slice(0,10)],['OSM 도로 비율',dataset.surface.roadFraction,dataset.osm.timestampUtc.slice(0,10)],['OSM 건물 비율',dataset.surface.buildingFraction,dataset.osm.timestampUtc.slice(0,10)]];for(const [label,values,date] of rows){const differentSatellite=label.startsWith('Sentinel')&&date!==scene().date;const r=values?.length===scene().values.length?pairSummary(values,scene().values,{mask:mask()}):null;addRow(root,[label,date||'자료 없음',differentSatellite?'—':fmt(r?.count,0),differentSatellite?'촬영일 다름 · 비교 보류':fmt(r?.correlation,3)]);}$('relationship-note').textContent='Sentinel-2 관계 분석은 LST와 같은 날짜에만 계산합니다. OSM은 2026년 등록 형상으로, 과거 LST와의 시점 차이가 있습니다. 토지 이용 변화와 공간 자기상관을 통제한 인과분석은 아직 수행하지 않았습니다.';}

function renderCover(){
  const root=$('cover-table');root.replaceChildren();$('cover-legend').replaceChildren();
  if(!landcover){$('cover-note').textContent='공식 자료가 연결되지 않았습니다.';return;}
  $('cover-note').textContent=`${landcover.edition} · 원영상 ${landcover.imageryDates?.join(', ')||'날짜 미제공'} · LST ${scene().date}. 자료 시점 차이가 있습니다.`;
  const rows=[];
  for(const [code,label] of Object.entries(landcover.legend)){
    const fractions=landcover.fractions?.[code];let area=0,weighted=0,observedArea=0,hotArea=0;
    for(let i=0;i<grid.width*grid.height;i++){
      if(!mask()[i])continue;const fraction=fractions?fractions[i]:(landcover.classes[i]===Number(code)?1:0);
      if(!finite(fraction)||fraction<=0)continue;const a=metrics.areas[i]*fraction;area+=a;
      if(finite(scene().values[i])){observedArea+=a;weighted+=a*scene().values[i];if(scene().values[i]>=clusters.threshold)hotArea+=a;}
    }
    if(!area)continue;rows.push({code,label,area,mean:observedArea?weighted/observedArea:null,hotArea});
  }
  rows.sort((a,b)=>b.area-a.area);
  for(const row of rows){const chip=node('span',`${row.code} ${row.label}`),dot=node('i');dot.style.background=color(Number(row.code),0,1,'classes');chip.prepend(dot);$('cover-legend').append(chip);addRow(root,[`${row.code} ${row.label}`,fmt(row.area/1e4,2),fmt(row.mean,2),fmt(row.hotArea/1e4,2)]);}
  if(!landcover.fractions)$('cover-note').textContent+=' 분율이 없어 최다 피복 셀 전체 면적에 따른 근사입니다.';
}
function drawFlux(canvas,vectors,max){
  if(!(max>0))return;const ctx=canvas.getContext('2d'),cw=canvas.width/grid.width,ch=canvas.height/grid.height;
  ctx.strokeStyle='#253b57';ctx.fillStyle='#253b57';ctx.lineWidth=Math.max(1.4,canvas.width/350);
  for(let row=0;row<grid.height;row+=2)for(let col=0;col<grid.width;col+=2){
    const i=row*grid.width+col,v=vectors[i];if(!mask()[i]||!v)continue;
    const magnitude=Math.hypot(...v);if(magnitude<max*.04)continue;
    const length=Math.min(cw,ch)*1.25*magnitude/max,x=(col+.5)*cw,y=(row+.5)*ch;
    const dx=v[0]/magnitude*length,dy=v[1]/magnitude*length,angle=Math.atan2(dy,dx),head=4;
    ctx.beginPath();ctx.moveTo(x-dx/2,y-dy/2);ctx.lineTo(x+dx/2,y+dy/2);ctx.stroke();
    ctx.beginPath();ctx.moveTo(x+dx/2,y+dy/2);ctx.lineTo(x+dx/2-head*Math.cos(angle-.5),y+dy/2-head*Math.sin(angle-.5));ctx.lineTo(x+dx/2-head*Math.cos(angle+.5),y+dy/2-head*Math.sin(angle+.5));ctx.closePath();ctx.fill();
  }
}

function renderSelection(){const i=selected;if(!metrics.centers[i])return;const [lng,lat]=metrics.centers[i],v=scene().values[i];$('cell-number').value=i+1;$('cell-detail').textContent=`격자 ${i+1} · ${fmt(lat,5)}, ${fmt(lng,5)} · ${finite(v)?fmt(v)+'°C':'유효 관측 없음'} · ${scene().date}${landcover?.classes[i]!=null?' · '+landcover.legend[landcover.classes[i]]:''}${!mask()[i]?' · 연구 경계 밖':''}`;$('set-a').disabled=$('set-b').disabled=!mask()[i]||!finite(v);const result=compareObservations(pickA,pickB);const entry=p=>p?`${p.label}: 격자 ${p.index+1}, ${fmt(p.value)}°C (${p.source.datetime.slice(0,10)})`:'선택 대기';$('ab-result').textContent=`${entry(pickA)} / ${entry(pickB)}. ${result.comparable?`B − A = ${signed(result.delta)}`:result.reason||'같은 장면의 두 격자를 선택하세요.'}`;}
function recordPoint(label){const p={index:selected,label,value:scene().values[selected],source:{id:scene().id,datetime:scene().datetime}};if(label==='A')pickA=p;else pickB=p;renderSelection();renderObservationMap();}

function renderModels(){if(!experiment)return;const hour=+$('model-hour').value,fluxMax=Math.max(0,...experiment.models.flatMap(m=>m.airFluxHourly[hour].filter(Boolean).map(v=>Math.hypot(...v))));const rows=$('model-table');rows.replaceChildren();for(let i=0;i<3;i++){const model=experiment.models[i],values=model.hourly[hour],stats=model.hourlyStats[hour],group=analyzeClusters({...grid,projection:'geographic',values,mask:mask(),threshold:experiment.threshold,epsMeters:+$('cluster-eps').value,minPoints:+$('cluster-min').value});drawRaster($(`model-map-${i}`),values,{min:24,max:50,changed:model.changedCells||[],hubs:i===2?experiment.plan.hubs:[]});if($('show-flux').checked)drawFlux($(`model-map-${i}`),model.airFluxHourly[hour],fluxMax);$(`model-stats-${i}`).textContent=`평균 ${fmt(stats.mean)}°C · 최고 ${fmt(stats.max)}°C`;addRow(rows,[`Model ${i+1}`,fmt(stats.mean),fmt(stats.max),fmt(stats.stdDev),fmt(stats.hotAreaM2/1e4,2),fmt(group.clusters.length,0),String(model.changedCells?.length||0)]);}
  $('flux-scale').textContent=`화살표: 가정한 30 m 대기층의 배경 대비 수평 열 수송량. 세 지도 공통 길이 척도 0–${fmt(fluxMax,0)} W/m. 음의 온도 편차에서는 열 수송 방향이 바람과 반대입니다. 실제 바람길 관측이 아닙니다.`;const plan=experiment.plan;$('model-scale').textContent=`모든 지도 24–50°C 고정 범위 · 녹색 테두리: 재료 변경 셀 · 녹색 점: MCLP 계획 거점. 고온 임계값 ${fmt(experiment.threshold)}°C는 Model 1의 ${fmt(experiment.metadata.evalHour,0)}시 P90으로 고정합니다.`;
  $('plan-summary').textContent=`변경 ${plan.budgetCount} / 가능 ${plan.eligibleCount}셀 (${plan.budgetPercent}%). 재료별 수량과 가정 비용 ${fmt(plan.costUnits,0)}단위를 Model 2·3에 동일 적용. ${plan.hubs.length}개 거점, 계획 반경 ${plan.coverageRadiusM} m. GA ${plan.generations}세대 · 실제 열모델로 ${plan.evaluatedLayouts}개 배치 평가 · 시드 ${plan.seed}. 수요: ${plan.demandWeight}. 목적함수: ${plan.objective}. Model 2 ${fmt(plan.objectiveFixed,3)} → Model 3 ${fmt(plan.objectiveOptimized,3)} (작을수록 유리).`;
  $('transport-note').textContent=`${experiment.metadata.boundary}. ${experiment.metadata.initialCondition}. ${experiment.metadata.limitations.join(' · ')}. 따라서 세 모델에서 경로가 달라졌다는 결론은 내리지 않으며, 같은 바람장에서 온도·열 수송 강도의 차이를 계산합니다.`;drawChart();
}
function drawChart(){const canvas=$('time-chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const lines=experiment.models.map(m=>m.hourlyStats.slice(0,24).map(v=>v.mean)),all=lines.flat().filter(finite),min=Math.floor(Math.min(...all)/5)*5,max=Math.ceil(Math.max(...all)/5)*5,pad={l:56,r:24,t:30,b:44};const x=i=>pad.l+i/23*(w-pad.l-pad.r),y=v=>h-pad.b-(v-min)/(max-min||1)*(h-pad.t-pad.b);ctx.font='18px sans-serif';ctx.fillStyle='#71806d';ctx.strokeStyle='#e3e7db';ctx.lineWidth=1;for(let j=0;j<=4;j++){const value=min+(max-min)*j/4;ctx.beginPath();ctx.moveTo(pad.l,y(value));ctx.lineTo(w-pad.r,y(value));ctx.stroke();ctx.fillText(fmt(value,0),8,y(value)+6);}for(const hour of [0,6,12,18,23])ctx.fillText(`${hour}시`,x(hour)-15,h-12);lines.forEach((line,i)=>{ctx.strokeStyle=modelColors[i];ctx.lineWidth=3;ctx.beginPath();line.forEach((v,k)=>k?ctx.lineTo(x(k),y(v)):ctx.moveTo(x(k),y(v)));ctx.stroke();ctx.fillStyle=modelColors[i];ctx.fillText(`Model ${i+1}`,w-350+i*110,20);});}
function runExperiment(){const id=++requestId;activeExperiment=id;$('run-model').disabled=true;$('model-status').textContent='동일 기상과 자원량으로 세 모델을 계산하고 후보 배치를 탐색하는 중입니다…';const weather=inputs.weather.dates.find(x=>x.date==='2024-08-29'&&x.status==='available');if(!weather){$('run-model').disabled=false;$('model-status').textContent='기준일 기상이 없어 계산할 수 없습니다.';return;}worker.postMessage({id,task:'experiment',dataset,options:{budgetPercent:+$('budget').value,seed:42,evalHour:+$('evaluation-hour').value,windEnabled:$('wind-enabled').checked,weather:weather.hourly}});}
function runValidation(){const id=++requestId;activeValidation=id;$('run-validation').disabled=true;$('validation-status').textContent='각 장면의 촬영일 기상으로 보정 없는 Model 1을 실행하고 있습니다…';worker.postMessage({id,task:'validation',dataset,scenes:inputs.landsat.scenes,weatherDates:inputs.weather.dates});}
worker.onmessage=({data})=>{if(data.task==='experiment'&&data.id===activeExperiment){$('run-model').disabled=false;if(data.error){$('model-status').textContent=data.error;$('model-status').classList.add('error');return;}experiment=data.result;$('export-models').disabled=false;$('model-status').textContent=`계산 완료 · 기상 2024-08-29 · 변경 셀 수·재료 수량 동일 · LST 보정 없음 · 평가 시각 ${fmt(experiment.metadata.evalHour,0)}시`;$('model-status').classList.remove('error');renderModels();renderQuestions();}if(data.task==='validation'&&data.id===activeValidation){$('run-validation').disabled=false;if(data.error){$('validation-status').textContent=data.error;$('validation-status').classList.add('error');return;}validationRows=data.result;$('validation-table').replaceChildren();for(const row of validationRows)addRow($('validation-table'),[row.date,row.unavailable?'—':new Date(Math.round(row.hour*3600)*1000).toISOString().slice(11,19),row.unavailable?row.reason:fmt(row.count,0),fmt(row.mae,2),fmt(row.rmse,2),fmt(row.bias,2),fmt(row.r2,3)]);$('validation-status').textContent='관측값을 초기화·보정·적합에 사용하지 않은 비교입니다. 가정 계수의 정확도가 검증된 것은 아니며, 아래 오차를 그대로 보고합니다.';renderQuestions();}};
worker.onerror=()=>{$('run-model').disabled=false;$('run-validation').disabled=false;$('model-status').textContent='계산 작업을 실행하지 못했습니다. 새로고침 후 다시 시도해 주세요.';};

function renderQuestions(){const q=[['재질·공간 배치와 LST는 어떤 관계인가?','실제 관측 + 등록 형상','같은 격자의 상관계수를 제공합니다. 재질은 미확인, OSM 형상은 관측 연도와 다릅니다.'],['Landsat·Sentinel-2·토지피복으로 고온 지역을 찾을 수 있는가?',landcover?'자료 연결':'일부 자료 확보',`Landsat LST와 ${inputs.sentinel2.status==='available'?'같은 날 Sentinel-2 지수 확보':'Sentinel-2 미확보'}. 공식 세분류 토지피복 ${landcover?'지도와 피복별 통계 연결':'원자료 미확보'}.`],['시간에 따른 열의 축적·확산·이동을 구현할 수 있는가?','가정 기반 모의계산','표면·기층·별도 대기층의 교환을 계산합니다. 실제 도시 바람길과 시간별 이동은 미검증입니다.'],['DBSCAN으로 고온 지역을 정량화할 수 있는가?','관측·모델에서 계산','미터 단위 이웃 거리, 군집별 면적·평균·최고온도와 잡음점을 제공합니다.'],['MCLP·유전 알고리즘으로 저감 자원의 위치를 찾을 수 있는가?',experiment?'모델 기반 탐색 완료':'모델 기반 탐색 가능','탐욕적 MCLP와 실제 열모델을 평가하는 GA입니다. 동일 자원량을 사용하며 전역 최적해를 보장하지 않습니다.'],['Model 1·2·3에는 어떤 차이가 있는가?',experiment?'동일 조건 비교 완료':'동일 조건 비교 가능','평균·최고·공간 표준편차·고온 면적을 공통 임계값으로 비교합니다. 실제 이동경로 비교는 미검증입니다.'],['Model 1은 실제 구월동 열환경을 얼마나 재현하는가?',validationRows?'보정 없는 오차 계산 완료':'독립 비교 가능','관측 시각과 날짜의 기상을 맞춰 MAE·RMSE·편향을 계산합니다. 같은 LST를 이용한 화소별 보정은 없습니다.']];$('question-cards').replaceChildren(...q.map(([title,status,body],i)=>{const el=node('article',undefined,'question');el.append(badge(`Q${i+1} · ${status}`,i===1&&!landcover),node('h3',title),node('p',body));return el;}));}
function renderSources(){const s=inputs.sentinel2;$('source-cards').replaceChildren(dataCard('Landsat 8/9 LST',`${inputs.landsat.scenes.length}개 실제 장면 · QA_PIXEL 제거 · 유효 하위 화소 80% 이상 셀의 평균 · 원 해상도 약 100m`,scene().source),dataCard('Sentinel-2 식생·시가지 지수',s.status==='available'?`${s.scene.date} · ${s.scene.platform} · B04/B08/B11 반사율 및 SCL 4·5·6 사용 · 정합 격자에서 NDVI·NDBI 평균`:'원자료 없음',s.scene?.source),dataCard('Open-Meteo ERA5',`${inputs.weather.dates.filter(x=>x.status==='available').map(x=>x.date).join(', ')} · 격자형 재분석 · 기온·일사·습도·풍향·풍속`,inputs.weather.documentation||'https://open-meteo.com/en/docs/historical-weather-api'),dataCard('OSM 건물·도로·녹지',`${dataset.osm.timestampUtc.slice(0,10)} 등록 형상. 과거 열 관측일과 다릅니다. 연구 모델의 재질은 가정값이며 기존 높이 사전값은 실측이 아닙니다.`,'https://www.openstreetmap.org/copyright'),dataCard('공식 세분류 토지피복',landcover?`${landcover.edition} · 원영상 ${landcover.imageryDates?.join(', ')||'날짜 미제공'} · 범주 다각형을 동일 격자에 집계`: '자료 미확보',landcover?.source),dataCard('연구 격자와 경계',`${grid.width} × ${grid.height}격자. ${grid.boundaryApproximation||'경계 내부 셀 전체를 포함하는 근사이며 행정구역의 정확한 면적과 다릅니다.'}`),dataCard('표면온도와 모델 가정','모의 온도는 보행 기온·체감온도가 아닙니다. 미확인 재질, 간단한 그늘, 초기 열 저장과 대기층 가정에 민감합니다.'));$('landcover-status').textContent=landcover?`${landcover.edition} · 원영상 ${landcover.imageryDates?.join(', ')||'날짜 미제공'}. 범주별 면적 분율과 최다 피복이 연결되었습니다.`:'공식 세분류 토지피복 원자료를 아직 확보하지 못했습니다. 해당 분석을 완료했다고 표시하지 않습니다.';}

async function init(){const responses=await Promise.all(['./data/guwol-data.json','./data/research-inputs.json'].map(async url=>{const r=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`연구 자료 불러오기 실패 (${r.status})`);return r.json();}));[dataset,inputs]=responses;grid=inputs.grid;dataset={...dataset,surface:{...dataset.surface,insideBoundary:grid.insideBoundary||dataset.surface.insideBoundary}};metrics=gridMetrics({...grid,projection:'geographic'});landcover=inputs.landcover.status==='available'?inputs.landcover:null;sceneIndex=Math.max(0,inputs.landsat.scenes.findIndex(s=>s.date==='2024-08-29'));$('observation-scene').replaceChildren(...inputs.landsat.scenes.map((s,i)=>{const option=node('option',`${s.date} · ${s.platform.replace('landsat-','Landsat ')}`);option.value=i;return option;}));$('observation-scene').value=sceneIndex;$('observation-scene').disabled=false;
  for(const option of $('observation-layer').options)if(['ndvi','ndbi'].includes(option.value))option.disabled=inputs.sentinel2.status!=='available';else if(option.value==='landcover')option.disabled=!landcover;
  selected=mask().findIndex(Boolean);$('cell-number').max=grid.width*grid.height;$('load-status').textContent=`자료 준비 완료 · ${inputs.landsat.scenes.length}개 Landsat 장면 · ${inputs.sentinel2.status==='available'?'실제 Sentinel-2 지수':'Sentinel-2 자료 미확보'} · 공식 토지피복 · 경계 내부 ${mask().filter(Boolean).length}셀`;renderObservation();renderSources();renderQuestions();$('run-model').disabled=false;$('run-validation').disabled=false;$('export-observations').disabled=false;$('model-status').textContent='기상 2024-08-29 · 원하는 변경 비율과 평가 시각을 선택해 계산하세요.';$('validation-status').textContent=`같은 촬영일의 기상을 확보한 ${inputs.weather.dates.filter(x=>x.status==='available').length}개 장면을 비교할 수 있습니다.`;document.querySelectorAll('[data-loading-disabled]').forEach(el=>el.disabled=false);runExperiment();runValidation();
}
$('observation-scene').onchange=()=>{sceneIndex=+$('observation-scene').value;renderObservation();renderSources();};$('observation-layer').onchange=renderObservationMap;$('show-clusters').onchange=renderObservationMap;$('recluster').onclick=()=>{try{renderObservation();if(experiment)renderModels();}catch(error){$('cluster-summary').textContent=error.message;}};
$('observation-map').onclick=event=>{if(!inputs)return;const canvas=$('observation-map'),rect=canvas.getBoundingClientRect(),actualRatio=canvas.width/canvas.height,displayRatio=rect.width/rect.height;let x=event.clientX-rect.left,y=event.clientY-rect.top,width=rect.width,height=rect.height;if(displayRatio>actualRatio){width=height*actualRatio;x-=(rect.width-width)/2;}else{height=width/actualRatio;y-=(rect.height-height)/2;}if(x<0||y<0||x>=width||y>=height)return;selected=Math.floor(y/height*grid.height)*grid.width+Math.floor(x/width*grid.width);renderSelection();};
$('pick-cell').onclick=()=>{if(!$('cell-number').checkValidity())return;selected=Math.max(0,Math.min(grid.width*grid.height-1,Math.floor(+$('cell-number').value)-1));renderSelection();};$('set-a').onclick=()=>recordPoint('A');$('set-b').onclick=()=>recordPoint('B');$('clear-ab').onclick=()=>{pickA=pickB=null;renderSelection();renderObservationMap();};$('budget').oninput=()=>{$('budget-value').textContent=`${$('budget').value}%`;if(experiment)$('model-status').textContent='입력 조건이 변경됐습니다. 현재 결과는 이전 계산이며 다시 계산해야 반영됩니다.';};$('model-hour').oninput=()=>{$('hour-value').textContent=`${String($('model-hour').value).padStart(2,'0')}:00`;if(experiment)renderModels();};$('wind-enabled').onchange=()=>{if(experiment)$('model-status').textContent='바람 조건이 변경됐습니다. 다시 계산해야 반영됩니다.';};$('evaluation-hour').onchange=()=>{if(experiment)$('model-status').textContent='배치 평가 시각이 변경됐습니다. 다시 계산하면 배치와 고온 기준에 반영됩니다.';};$('show-flux').onchange=renderModels;$('run-model').onclick=()=>{if($('evaluation-hour').checkValidity())runExperiment();};$('run-validation').onclick=runValidation;
$('export-observations').onclick=()=>{const rows=[['scene_id','acquisition_utc','cell','longitude','latitude','lst_c','cluster_id','cell_area_m2']];scene().values.forEach((v,i)=>{if(mask()[i])rows.push([scene().id,scene().datetime,i+1,...metrics.centers[i],v,clusters.labels[i],metrics.areas[i]]);});download(`guwol-observations-${scene().date}.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'));};
$('export-models').onclick=()=>{const hour=+$('model-hour').value,rows=[['cell','longitude','latitude','hour_kst','model1_c','model2_c','model3_c','model3_minus_model1_c','common_hot_threshold_c','material1','material2','material3']];for(let i=0;i<grid.width*grid.height;i++)if(mask()[i]){const values=experiment.models.map(m=>m.hourly[hour][i]);rows.push([i+1,...metrics.centers[i],hour,...values,values[2]-values[0],experiment.threshold,...experiment.models.map(m=>MATERIALS[m.types[i]].name)]);}download(`guwol-models-${hour}h.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'));};
$('landcover-file').onchange=async()=>{try{const file=$('landcover-file').files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('2MB 이하의 정합된 JSON 파일을 선택해 주세요.');const value=JSON.parse(await file.text());if(value.classes?.length!==grid.width*grid.height||value.grid?.width!==grid.width||value.grid?.height!==grid.height||value.grid?.bbox?.length!==4||!value.grid?.bbox?.every((n,i)=>Math.abs(n-grid.bbox[i])<1e-7)||!/^https:\/\//.test(value.source)||!value.edition||!value.sourceCRS||!value.method||value.grid.projection!=='EPSG:4326'||value.grid.order!=='row-major north-to-south'||!value.legend)throw Error('격자·경계·classes·source·edition·sourceCRS·method·legend가 포함된 정합 파일이 필요합니다. 재현 문서의 자료 형식을 확인하세요.');if(value.classes.some((x,i)=>(!mask()[i]&&x!==null)||(x!==null&&(!Number.isInteger(x)||typeof value.legend[String(x)]!=='string'))))throw Error('모든 분류 코드는 legend에 정의된 정수이거나 null이어야 합니다.');if(value.fractions&&Object.values(value.fractions).some(a=>!Array.isArray(a)||a.length!==grid.width*grid.height||a.some((x,i)=>!mask()[i]?x!==null:(!finite(x)||x<0||x>1))))throw Error('분율은 경계 내부에서 0–1의 수이며 경계 밖에서는 null이어야 합니다.');landcover=value;$('observation-layer').querySelector('option[value="landcover"]').disabled=false;$('observation-layer').value='landcover';$('landcover-import-status').textContent=`${file.name} 연결 완료 · ${value.edition} · ${String(value.source)} · 브라우저 내에서만 사용`;renderSources();renderQuestions();renderCover();renderSelection();renderObservationMap();}catch(error){$('landcover-import-status').textContent=error.message;}};
document.querySelectorAll('main button,main select,main input').forEach(el=>{if(!el.disabled){el.dataset.loadingDisabled='';el.disabled=true;}});
init().catch(error=>{$('load-status').textContent=error.message;$('load-status').classList.add('error');console.error(error);});
